version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: cicd        # your Docker Hub repo name, e.g., <username>/<repo-name>
    DOCKER_USERNAME: sharpandtannan   # your Docker Hub username
    DOCKER_PASSWORD: sharptannan
    AWS_REGION: ap-south-1         # change to your region
    IMAGE_TAG: test:1
  git-credential-helper: yes

phases:
  pre_build:
    commands:
      - echo "Logging into Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      # Derive image tag (you can change this logic)
      - echo "Setting IMAGE_TAG..."
      # Or: IMAGE_TAG=${CODEBUILD_BUILD_NUMBER}
      - echo "Image tag = $IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push $DOCKER_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
